#!/bin/bash

# Exit the script if no bucket name is provided
if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

# Exit the script if no path to a directory is provided
if [ -z "$2" ]; then
    echo "No directory path provided"
    exit 1
fi

BUCKET_NAME=$1
DIRECTORY_PATH=$2

# Exit the script if the directory doesn't exist
if [ ! -d "$DIRECTORY_PATH" ]; then
    echo "Error: Directory '$DIRECTORY_PATH' does not exist."
    exit 1
fi

aws s3 sync "$DIRECTORY_PATH" s3://$BUCKET_NAME/files
